# Contains automatic fixes for some deprecations introduced in Drupal 8.0.
services:
  DrupalRector\Rector\Deprecation\Drupal8\DBInsertRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\DBSelectRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\DBQueryRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\DBDeleteRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\DBUpdateRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\DrupalRenderRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\DrupalRenderRootRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\DrupalURLRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\DrupalLRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\DrupalRealpathRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\EntityCreateRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\EntityInterfaceLinkRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\EntityInterfaceUrlInfoRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\EntityLoadRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\EntityManagerRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\FormatDateRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\FileLoadRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\LinkGeneratorTraitLRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\NodeLoadRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\SafeMarkupFormatRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\UserLoadRector: ~
