# Contains automatic fixes for some deprecations introduced in Drupal 8.6.
services:
  DrupalRector\Rector\Deprecation\Drupal8\UnicodeStrlenRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\UnicodeStrtolowerRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\UnicodeSubstrRector: ~
