# Contains automatic fixes for some deprecations introduced in Drupal 8.7.
services:
  DrupalRector\Rector\Deprecation\Drupal8\FilePrepareDirectoryRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\FileCreateDirectoryRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\FileExistsReplaceRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\FileUnmanagedSaveDataRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\FileModifyPermissionsRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\FileExistsRenameRector: ~
