# Contains automatic fixes for some deprecations introduced in Drupal 8.8.
services:
  DrupalRector\Rector\Deprecation\Drupal8\PathAliasManagerServiceNameRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\PathAliasWhitelistServiceNameRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\PathSubscriberServiceNameRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\PathProcessorAliasServiceNameRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\PathAliasRepositoryRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\FileDefaultSchemeRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\EntityGetDisplayRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\EntityGetFormDisplayRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\EntityTypeGetLowercaseLabelRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\FileScanDirectoryRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\FileDirectoryTempRector: ~
  DrupalRector\Rector\Deprecation\Drupal8\FileUriTargetRector: ~
