# Contains automatic fixes for some deprecations introduced in Drupal 8.5.
services:
    DrupalRector\Rector\Deprecation\Drupal8\DrupalSetMessageRector: ~
    DrupalRector\Rector\Deprecation\Drupal8\DatetimeDateStorageFormatRector: ~
    DrupalRector\Rector\Deprecation\Drupal8\DatetimeDatetimeStorageFormatRector: ~
    DrupalRector\Rector\Deprecation\Drupal8\DatetimeStorageTimezoneRector: ~
