# Contains automatic fixes for some deprecations introduced in Drupal 8.4.
services:
    DrupalRector\Rector\Deprecation\Drupal8\BrowserTestBaseGetMockRector: ~
    DrupalRector\Rector\Deprecation\Drupal8\KernelTestBaseGetMockRector: ~
    DrupalRector\Rector\Deprecation\Drupal8\UnitTestCaseGetMockRector: ~
